### ISSUE TITLE
请问这个支持解码GB2312字符集编码的吗？

### ISSUE THREAD

**Issue by GitHanDong** [tibetty/decodeUriComponent#1]
RT

**Comment by tibetty** [comment]
uriencode（百分號編碼）標準貌似規定要用utf-8的編碼方式(參見
https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_in_a_URI，“The
generic URI syntax mandates that new URI schemes that provide for the
representation of character data in a URI must, in effect, represent
characters from the unreserved set without translation, and should convert
all other characters to bytes according to UTF-8
<https://en.wikipedia.org/wiki/UTF-8>, and then percent-encode those
values. This requirement was introduced in January 2005 with the
publication of RFC 3986 <https://tools.ietf.org/html/rfc3986>. URI schemes
introduced before this date are not affected.”)。
你的具體需求是什麼？能貼一段編碼後的字符串看下嗎？

**Comment by GitHanDong** [comment]
例如：“服装”用utf8字符集decode之后是“%e6%9c%8d%e8%a3%85”，而用gb2313字符集decode之后是“%b7%fe%d7%b0”。
当编码是“%b7%fe%d7%b0”（即用GB2313字符集编码），用utf8字符集解码就会出现乱码“��װ”。

http://tool.chinaz.com/tools/urlencode.aspx
您可以到这个网站测试。

**Comment by tibetty** [comment]
收到了解，要實現這個，需要一個gbk轉unicode的庫。回頭我給你寫一個實現，但是考慮到這個不在標準要求之內，就不加入代碼倉庫裡面了。

**Comment by tibetty** [comment]
const iconv = require('iconv-lite');
  
let decodeUriComponentGBK = s => {
        let regex = /(%([0-9a-f]{2}))+/gi;
        let res = null, lastIdx = 0, parts = [];
        while (res = regex.exec(s)) {
                parts.push(s.substring(lastIdx, regex.lastIndex - res[0].length));
                parts.push(iconv.decode(new Buffer(res[0].split(/%([0-9a-f]{2})/).reduce((buff, v) => {
                        if (v !== '') buff.push(parseInt(v, 16));
                        return buff;
                }, [])), 'gbk'));
                lastIdx = regex.lastIndex;
        }
        return parts.join('');
}

**Comment by tibetty** [comment]
const iconv = require('iconv-lite');
      
    const decodeUriComponentGBK = s => {
        let regex = /(%([0-9a-f]{2}))+/gi;
        let res = null, lastIdx = 0, parts = [];
        while (res = regex.exec(s)) {
            parts.push(s.substring(lastIdx, regex.lastIndex - res[0].length));
            parts.push(iconv.decode(new Buffer(res[0].split(/%([0-9a-f]{2})/).reduce((buff, v) => {
                if (v !== '') buff.push(parseInt(v, 16));
                return buff;
            }, [])), 'gbk'));
            lastIdx = regex.lastIndex;
        }
        return parts.join('');
    }

調用的時候直接用decodeUriComponentGBK(yourString)即可。

**Comment by tibetty** [comment]
I've added encoding support to my module.  Please tell me if your problem has been solved and I will close this issue ASAP.

**Comment by GitHanDong** [comment]
OK！Thanks！
感谢！还没有测试是否解决，感谢您的辛苦付出！

**Comment by tibetty** [comment]
用decodeUriComponent('%b7%fe%d7%b0', 'gbk')試一下即可。

**Comment by GitHanDong** [comment]
万分感谢！👍👍👍！
